[package]
name = "wasm-main-module"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.83"
smallvec = "1"
wasm-bindgen = "0.2"

[profile.dev]
# Never build without optimizations
opt-level = 1
# We do not debug anyway
debug = "line-tables-only"

[profile.release]
# Enable backtrace info
# debug = "line-tables-only"
# Enable this for faster builds
debug = "none"
